version: '3.9'

services:
  db:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
         - 27017:27017
    volumes:
      - .:/data/mongo
  app:
    container_name: app
    image: python:3.9
    build: .
    command: python src/main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - 3000:3000
