version: '3.8'

services:
  db:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  app:
    container_name: app
    image: python:3.8
    build: .
    command: python src/main.py
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db