name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Update toml
      run: |
        version=$(date +%Y%m%d%H%M%S)
        sed -i "s/^version.*/version = \"$version\"/" pyproject.toml

    - name: poetry install
      run: |
        pip install -r requirements.txt
        python -m pip install poetry

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: poetry lint
      run: |
        pip install pylint
        pylint ./src
      continue-on-error: true
    
    - name: poetry tests
      run: |
        poetry run pytest ./tests

    - name: poetry publish
      env:
        POETRY_USERNAME: ${{secrets.POETRY_USERNAME}}
        POETRY_PASSWORD: ${{secrets.POETRY_PASSWORD}}
      run: |
        poetry publish --build -u $POETRY_USERNAME -p $POETRY_PASSWORD
