name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: poetry lint
      run: |
        pip install poetry && poetry run pylint ./src
    
    - name: poetry tests
      run: |
        pip install poetry && poetry run pytest ./tests

    - name: poetry install
      run: |
        pip install poetry && poetry install

    - name: poetry publish
      env:
        POETRY_USERNAME: ${{secrets.POETRY_USERNAME}}
        POETRY_PASSWORD: ${{secrets.POETRY_PASSWORD}}
      run: |
        pip install poetry && poetry publish --build -u $POETRY_USERNAME -p $POETRY_PASSWORD 
