name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up --build -d
  
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: poetry lint
      run: |
        pip install pylint
        pylint ./src
      continue-on-error: true

  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: poetry tests
      run: |
        poetry run pytest ./tests

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Update toml
      run: |
        version=$(date +%Y%m%d%H%M%S)
        sed -i "s/^version.*/version = \"$version\"/" pyproject.toml

    - name: poetry install
      run: |
        pip install -r requirements.txt
        python -m pip install poetry

    - name: Install Poetry
      uses: snok/install-poetry@v1
    
    - name: poetry publish
      env:
        POETRY_USERNAME: ${{secrets.POETRY_USERNAME}}
        POETRY_PASSWORD: ${{secrets.POETRY_PASSWORD}}
      run: |
        poetry publish --build -u $POETRY_USERNAME -p $POETRY_PASSWORD

  docs:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python and pip
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
        
    - name: Install sphinx, doxygen and breathe
      run: |
        sudo apt install doxygen
        pip install breathe
        pip install -U sphinx
        pip install sphinx-rtd-theme
        
    - name: Run doxygen
      run: doxygen Doxyfile
    
    - name: Run sphinx
      working-directory: ./docs
      run: make html