name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build -d

    - name: Config
      run: |
        docker-compose run app bash; pip install poetry

    - name: poetry install
      run: |
        docker-compose run app bash -c "poetry add `cat requirements.txt`; poetry install --no-interaction

    - name: poetry lint
      run: |
        docker-compose run app bash; poetry run pylint ./src
    
    - name: poetry tests
      run: |
        docker-compose run app bash; poetry run pytest ./tests

    - name: poetry publish
      env:
        POETRY_USERNAME: ${{secrets.POETRY_USERNAME}}
        POETRY_PASSWORD: ${{secrets.POETRY_PASSWORD}}
      run: |
        docker-compose run app bash; poetry publish --build -u $POETRY_USERNAME -p $POETRY_PASSWORD 
